// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/nikonhub/ai-learn-cli/ent/generatedproblem"
	"github.com/nikonhub/ai-learn-cli/ent/item"
	"github.com/nikonhub/ai-learn-cli/ent/predicate"
)

// GeneratedProblemQuery is the builder for querying GeneratedProblem entities.
type GeneratedProblemQuery struct {
	config
	ctx        *QueryContext
	order      []generatedproblem.OrderOption
	inters     []Interceptor
	predicates []predicate.GeneratedProblem
	withItem   *ItemQuery
	withFKs    bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the GeneratedProblemQuery builder.
func (gpq *GeneratedProblemQuery) Where(ps ...predicate.GeneratedProblem) *GeneratedProblemQuery {
	gpq.predicates = append(gpq.predicates, ps...)
	return gpq
}

// Limit the number of records to be returned by this query.
func (gpq *GeneratedProblemQuery) Limit(limit int) *GeneratedProblemQuery {
	gpq.ctx.Limit = &limit
	return gpq
}

// Offset to start from.
func (gpq *GeneratedProblemQuery) Offset(offset int) *GeneratedProblemQuery {
	gpq.ctx.Offset = &offset
	return gpq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (gpq *GeneratedProblemQuery) Unique(unique bool) *GeneratedProblemQuery {
	gpq.ctx.Unique = &unique
	return gpq
}

// Order specifies how the records should be ordered.
func (gpq *GeneratedProblemQuery) Order(o ...generatedproblem.OrderOption) *GeneratedProblemQuery {
	gpq.order = append(gpq.order, o...)
	return gpq
}

// QueryItem chains the current query on the "item" edge.
func (gpq *GeneratedProblemQuery) QueryItem() *ItemQuery {
	query := (&ItemClient{config: gpq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := gpq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := gpq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(generatedproblem.Table, generatedproblem.FieldID, selector),
			sqlgraph.To(item.Table, item.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, generatedproblem.ItemTable, generatedproblem.ItemColumn),
		)
		fromU = sqlgraph.SetNeighbors(gpq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first GeneratedProblem entity from the query.
// Returns a *NotFoundError when no GeneratedProblem was found.
func (gpq *GeneratedProblemQuery) First(ctx context.Context) (*GeneratedProblem, error) {
	nodes, err := gpq.Limit(1).All(setContextOp(ctx, gpq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{generatedproblem.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (gpq *GeneratedProblemQuery) FirstX(ctx context.Context) *GeneratedProblem {
	node, err := gpq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first GeneratedProblem ID from the query.
// Returns a *NotFoundError when no GeneratedProblem ID was found.
func (gpq *GeneratedProblemQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = gpq.Limit(1).IDs(setContextOp(ctx, gpq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{generatedproblem.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (gpq *GeneratedProblemQuery) FirstIDX(ctx context.Context) int {
	id, err := gpq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single GeneratedProblem entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one GeneratedProblem entity is found.
// Returns a *NotFoundError when no GeneratedProblem entities are found.
func (gpq *GeneratedProblemQuery) Only(ctx context.Context) (*GeneratedProblem, error) {
	nodes, err := gpq.Limit(2).All(setContextOp(ctx, gpq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{generatedproblem.Label}
	default:
		return nil, &NotSingularError{generatedproblem.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (gpq *GeneratedProblemQuery) OnlyX(ctx context.Context) *GeneratedProblem {
	node, err := gpq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only GeneratedProblem ID in the query.
// Returns a *NotSingularError when more than one GeneratedProblem ID is found.
// Returns a *NotFoundError when no entities are found.
func (gpq *GeneratedProblemQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = gpq.Limit(2).IDs(setContextOp(ctx, gpq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{generatedproblem.Label}
	default:
		err = &NotSingularError{generatedproblem.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (gpq *GeneratedProblemQuery) OnlyIDX(ctx context.Context) int {
	id, err := gpq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of GeneratedProblems.
func (gpq *GeneratedProblemQuery) All(ctx context.Context) ([]*GeneratedProblem, error) {
	ctx = setContextOp(ctx, gpq.ctx, ent.OpQueryAll)
	if err := gpq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*GeneratedProblem, *GeneratedProblemQuery]()
	return withInterceptors[[]*GeneratedProblem](ctx, gpq, qr, gpq.inters)
}

// AllX is like All, but panics if an error occurs.
func (gpq *GeneratedProblemQuery) AllX(ctx context.Context) []*GeneratedProblem {
	nodes, err := gpq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of GeneratedProblem IDs.
func (gpq *GeneratedProblemQuery) IDs(ctx context.Context) (ids []int, err error) {
	if gpq.ctx.Unique == nil && gpq.path != nil {
		gpq.Unique(true)
	}
	ctx = setContextOp(ctx, gpq.ctx, ent.OpQueryIDs)
	if err = gpq.Select(generatedproblem.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (gpq *GeneratedProblemQuery) IDsX(ctx context.Context) []int {
	ids, err := gpq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (gpq *GeneratedProblemQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, gpq.ctx, ent.OpQueryCount)
	if err := gpq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, gpq, querierCount[*GeneratedProblemQuery](), gpq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (gpq *GeneratedProblemQuery) CountX(ctx context.Context) int {
	count, err := gpq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (gpq *GeneratedProblemQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, gpq.ctx, ent.OpQueryExist)
	switch _, err := gpq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (gpq *GeneratedProblemQuery) ExistX(ctx context.Context) bool {
	exist, err := gpq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the GeneratedProblemQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (gpq *GeneratedProblemQuery) Clone() *GeneratedProblemQuery {
	if gpq == nil {
		return nil
	}
	return &GeneratedProblemQuery{
		config:     gpq.config,
		ctx:        gpq.ctx.Clone(),
		order:      append([]generatedproblem.OrderOption{}, gpq.order...),
		inters:     append([]Interceptor{}, gpq.inters...),
		predicates: append([]predicate.GeneratedProblem{}, gpq.predicates...),
		withItem:   gpq.withItem.Clone(),
		// clone intermediate query.
		sql:  gpq.sql.Clone(),
		path: gpq.path,
	}
}

// WithItem tells the query-builder to eager-load the nodes that are connected to
// the "item" edge. The optional arguments are used to configure the query builder of the edge.
func (gpq *GeneratedProblemQuery) WithItem(opts ...func(*ItemQuery)) *GeneratedProblemQuery {
	query := (&ItemClient{config: gpq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	gpq.withItem = query
	return gpq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		ProblemText string `json:"problem_text,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.GeneratedProblem.Query().
//		GroupBy(generatedproblem.FieldProblemText).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (gpq *GeneratedProblemQuery) GroupBy(field string, fields ...string) *GeneratedProblemGroupBy {
	gpq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &GeneratedProblemGroupBy{build: gpq}
	grbuild.flds = &gpq.ctx.Fields
	grbuild.label = generatedproblem.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		ProblemText string `json:"problem_text,omitempty"`
//	}
//
//	client.GeneratedProblem.Query().
//		Select(generatedproblem.FieldProblemText).
//		Scan(ctx, &v)
func (gpq *GeneratedProblemQuery) Select(fields ...string) *GeneratedProblemSelect {
	gpq.ctx.Fields = append(gpq.ctx.Fields, fields...)
	sbuild := &GeneratedProblemSelect{GeneratedProblemQuery: gpq}
	sbuild.label = generatedproblem.Label
	sbuild.flds, sbuild.scan = &gpq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a GeneratedProblemSelect configured with the given aggregations.
func (gpq *GeneratedProblemQuery) Aggregate(fns ...AggregateFunc) *GeneratedProblemSelect {
	return gpq.Select().Aggregate(fns...)
}

func (gpq *GeneratedProblemQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range gpq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, gpq); err != nil {
				return err
			}
		}
	}
	for _, f := range gpq.ctx.Fields {
		if !generatedproblem.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if gpq.path != nil {
		prev, err := gpq.path(ctx)
		if err != nil {
			return err
		}
		gpq.sql = prev
	}
	return nil
}

func (gpq *GeneratedProblemQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*GeneratedProblem, error) {
	var (
		nodes       = []*GeneratedProblem{}
		withFKs     = gpq.withFKs
		_spec       = gpq.querySpec()
		loadedTypes = [1]bool{
			gpq.withItem != nil,
		}
	)
	if gpq.withItem != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, generatedproblem.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*GeneratedProblem).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &GeneratedProblem{config: gpq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, gpq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := gpq.withItem; query != nil {
		if err := gpq.loadItem(ctx, query, nodes, nil,
			func(n *GeneratedProblem, e *Item) { n.Edges.Item = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (gpq *GeneratedProblemQuery) loadItem(ctx context.Context, query *ItemQuery, nodes []*GeneratedProblem, init func(*GeneratedProblem), assign func(*GeneratedProblem, *Item)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*GeneratedProblem)
	for i := range nodes {
		if nodes[i].item_generated_problems == nil {
			continue
		}
		fk := *nodes[i].item_generated_problems
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(item.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "item_generated_problems" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (gpq *GeneratedProblemQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := gpq.querySpec()
	_spec.Node.Columns = gpq.ctx.Fields
	if len(gpq.ctx.Fields) > 0 {
		_spec.Unique = gpq.ctx.Unique != nil && *gpq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, gpq.driver, _spec)
}

func (gpq *GeneratedProblemQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(generatedproblem.Table, generatedproblem.Columns, sqlgraph.NewFieldSpec(generatedproblem.FieldID, field.TypeInt))
	_spec.From = gpq.sql
	if unique := gpq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if gpq.path != nil {
		_spec.Unique = true
	}
	if fields := gpq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, generatedproblem.FieldID)
		for i := range fields {
			if fields[i] != generatedproblem.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := gpq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := gpq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := gpq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := gpq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (gpq *GeneratedProblemQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(gpq.driver.Dialect())
	t1 := builder.Table(generatedproblem.Table)
	columns := gpq.ctx.Fields
	if len(columns) == 0 {
		columns = generatedproblem.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if gpq.sql != nil {
		selector = gpq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if gpq.ctx.Unique != nil && *gpq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range gpq.predicates {
		p(selector)
	}
	for _, p := range gpq.order {
		p(selector)
	}
	if offset := gpq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := gpq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// GeneratedProblemGroupBy is the group-by builder for GeneratedProblem entities.
type GeneratedProblemGroupBy struct {
	selector
	build *GeneratedProblemQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (gpgb *GeneratedProblemGroupBy) Aggregate(fns ...AggregateFunc) *GeneratedProblemGroupBy {
	gpgb.fns = append(gpgb.fns, fns...)
	return gpgb
}

// Scan applies the selector query and scans the result into the given value.
func (gpgb *GeneratedProblemGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, gpgb.build.ctx, ent.OpQueryGroupBy)
	if err := gpgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*GeneratedProblemQuery, *GeneratedProblemGroupBy](ctx, gpgb.build, gpgb, gpgb.build.inters, v)
}

func (gpgb *GeneratedProblemGroupBy) sqlScan(ctx context.Context, root *GeneratedProblemQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(gpgb.fns))
	for _, fn := range gpgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*gpgb.flds)+len(gpgb.fns))
		for _, f := range *gpgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*gpgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := gpgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// GeneratedProblemSelect is the builder for selecting fields of GeneratedProblem entities.
type GeneratedProblemSelect struct {
	*GeneratedProblemQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (gps *GeneratedProblemSelect) Aggregate(fns ...AggregateFunc) *GeneratedProblemSelect {
	gps.fns = append(gps.fns, fns...)
	return gps
}

// Scan applies the selector query and scans the result into the given value.
func (gps *GeneratedProblemSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, gps.ctx, ent.OpQuerySelect)
	if err := gps.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*GeneratedProblemQuery, *GeneratedProblemSelect](ctx, gps.GeneratedProblemQuery, gps, gps.inters, v)
}

func (gps *GeneratedProblemSelect) sqlScan(ctx context.Context, root *GeneratedProblemQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(gps.fns))
	for _, fn := range gps.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*gps.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := gps.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
