// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/nikonhub/ai-learn-cli/ent/itemprogress"
	"github.com/nikonhub/ai-learn-cli/ent/predicate"
)

// ItemProgressDelete is the builder for deleting a ItemProgress entity.
type ItemProgressDelete struct {
	config
	hooks    []Hook
	mutation *ItemProgressMutation
}

// Where appends a list predicates to the ItemProgressDelete builder.
func (ipd *ItemProgressDelete) Where(ps ...predicate.ItemProgress) *ItemProgressDelete {
	ipd.mutation.Where(ps...)
	return ipd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ipd *ItemProgressDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, ipd.sqlExec, ipd.mutation, ipd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (ipd *ItemProgressDelete) ExecX(ctx context.Context) int {
	n, err := ipd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ipd *ItemProgressDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(itemprogress.Table, sqlgraph.NewFieldSpec(itemprogress.FieldID, field.TypeInt))
	if ps := ipd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, ipd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	ipd.mutation.done = true
	return affected, err
}

// ItemProgressDeleteOne is the builder for deleting a single ItemProgress entity.
type ItemProgressDeleteOne struct {
	ipd *ItemProgressDelete
}

// Where appends a list predicates to the ItemProgressDelete builder.
func (ipdo *ItemProgressDeleteOne) Where(ps ...predicate.ItemProgress) *ItemProgressDeleteOne {
	ipdo.ipd.mutation.Where(ps...)
	return ipdo
}

// Exec executes the deletion query.
func (ipdo *ItemProgressDeleteOne) Exec(ctx context.Context) error {
	n, err := ipdo.ipd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{itemprogress.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ipdo *ItemProgressDeleteOne) ExecX(ctx context.Context) {
	if err := ipdo.Exec(ctx); err != nil {
		panic(err)
	}
}
