// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// GeneratedProblem is the predicate function for generatedproblem builders.
type GeneratedProblem func(*sql.Selector)

// Item is the predicate function for item builders.
type Item func(*sql.Selector)

// ItemProgress is the predicate function for itemprogress builders.
type ItemProgress func(*sql.Selector)

// Settings is the predicate function for settings builders.
type Settings func(*sql.Selector)

// Topic is the predicate function for topic builders.
type Topic func(*sql.Selector)
